Update task dependencies
equinor/isar pull request #186
Opened 2022-01-24 17:20 UTC by vetlek

Closes #166

2022-01-25 09:32 UTC, aestene commented on src/robot_interface/models/mission/task.py
> +        return Inspection
```suggestion
    def get_inspection_type(self):
        return type(self)
```

2022-01-26 14:47 UTC, aestene commented on src/isar/state_machine/state_machine.py
> +from black import re
Should this be here?

2022-01-26 14:49 UTC, aestene requested changes
One minor comment for a line that might be removed, otherwise good.

2022-01-26 14:59 UTC, vetlek commented on src/isar/state_machine/state_machine.py
> +from black import re
Nope

2022-01-27 08:13 UTC, aestene approved these changes
LGTM

2022-01-27 08:14 UTC, merged