Mission to interface
equinor/isar pull request #423
Opened 2023-03-06 12:53 UTC by Christdej

2023-03-06 13:24 UTC, Christdej commented
Requires a new version and changes in robot-repos to avoid breaking

2023-03-23 15:00 UTC, tsundvoll requested changes
Overall the changes looks good, just a few comments.

2023-03-24 07:59 UTC, tsundvoll commented on src/isar/models/communication/message.py
> +from isar.models.mission_metadata.mission_metadata import MissionMetadata
I agree, but this is how isort sort on my side. Might be some PyCharm isort setting that are strange, or that the scope of the editor is set to one level above isar.

2023-03-24 08:18 UTC, aestene commented on src/isar/models/communication/message.py
> +from isar.models.mission_metadata.mission_metadata import MissionMetadata
Alternatively, there may be some isort settings on your side which hasn't been properly adjusted to the correct one that you will find in PyCharm... Tricky question this :D

2023-03-24 08:21 UTC, aestene commented on src/isar/models/communication/message.py
> +from isar.models.mission_metadata.mission_metadata import MissionMetadata
I resaved the file and it grouped them together so I'm not sure what happened.

2023-03-24 08:29 UTC, aestene commented on src/isar/services/utilities/scheduling_utilities.py
> +        mission_metadata: MissionMetadata,  # type: ignore
Removed

2023-03-24 08:31 UTC, aestene commented on tests/isar/services/readers/test_mission_reader.py
> +        == MissionMetadata.vertical_reference_system
Removed them

2023-03-24 08:33 UTC, aestene commented on tests/isar/state_machine/test_state_machine.py
> +    metadata: MissionMetadata = MissionMetadata(mission.id)
Added new issue in #438

2023-03-24 08:39 UTC, aestene commented on src/isar/apis/schedule/scheduling_controller.py
> +            ),
I wrote out the for-loop instead.

2023-03-24 09:23 UTC, merged