Run send mission in separate thread
equinor/isar pull request #70
Opened 2021-11-04 09:14 UTC by vetlek

2021-11-04 09:54 UTC, Eddasol approved these changes
LGTM

2021-11-04 10:30 UTC, oysand commented on src/isar/state_machine/states/send.py
> +            self.send_thread.join()
Could we risk the code hanging on this step if something is holding up the thread?

2021-11-04 10:31 UTC, oysand commented on src/isar/state_machine/states/send.py
> +            self.send_thread.join()
Well, that is the purpose of join come to think on it... What I mean is that is there a case where the code could hang indefinitely, if so, should we implement some sort of timeout?

2021-11-04 10:34 UTC, oysand commented on src/isar/state_machine/states/send.py
> +                    args=(
Could we list which input each of these would be, for instance: schedule_step_func=self.state_machine.robot.schedule_step?

2021-11-04 10:41 UTC, oysand commented on src/isar/state_machine/states/send.py
> +def send_mission_thread(
Would it be better to have this function as part of the class?

2021-11-04 10:46 UTC, oysand requested changes
See comments/questions

2021-11-05 09:46 UTC, oysand commented on src/isar/services/utilities/threaded_request.py
> +    def start_thread(self, *args) -> bool:
Should we specify which args one can input?

2021-11-05 10:08 UTC, oysand commented on src/isar/state_machine/states/send.py
> +            if not self.send_thread.is_thread_alive():
Handle thread specific requirements inside ThreadRequest. Could try try except?

2021-11-05 10:55 UTC, oysand commented on src/isar/state_machine/states/send.py
> +                continue
Consider a short sleep?

2021-11-05 12:20 UTC, Christdej approved these changes

2021-11-05 12:23 UTC, merged